---
title: "Woods Hole SLR Data & Rates"
subtitle: "Produced for Martha’s Vineyard Commission" 
date: "`r Sys.Date()`"
author:
  - name: Laura Feher
    affiliations: 
    - name: NPS NCBN I&M Network
format: html
toc: true 
code-fold: true
code-overflow: wrap
embed-resources: true
execute:
  message: false
  warning: false
editor: visual
---

```{r Load packages}
#| include: false

library(tidyverse)
library(readxl)
library(stringr)
library(mgcv)
library(gratia)
```

## 1. Get the most recent long-term SLR rate from NOAA

```{r}

woods_hole_slr_long <- as.data.frame(readr::read_csv("https://tidesandcurrents.noaa.gov/sltrends/data/USStationsLinearSeaLevelTrends.csv", show_col_types = FALSE, name_repair = make.names)) %>%
  rename_with(., ~str_replace_all(.x, "\\.{2,}", ".")) %>%
  rename_with(., ~str_replace_all(.x, "X", "Perc")) %>%
  filter(Station.Name == "Woods Hole, MA")

woods_hole_slr_long
```

## 2. Get SLR data from the Woods Hole NOAA gauge and Calculate recent SLR

```{r}

woods_hole_slr_data <- as.data.frame(readr::read_csv("https://tidesandcurrents.noaa.gov/sltrends/data/8447930_meantrend.csv", skip = 5, show_col_types = FALSE)) 

woods_hole_slr_recent <- woods_hole_slr_data %>%
  mutate(date = as.Date(paste0(Month, "/", "1/", Year), format = "%m/%d/%Y")) %>% 
  filter(date >= as.Date("2001-01-01") & date <= as.Date("2019-12-31")) %>%
  mutate(min_date = min(date),
         max_date = max(date),
         yr = as.numeric(date - min_date)/365.25,
         Monthly_MSL_mm = Monthly_MSL * 1000) %>% # convert to millimeters for comparisons to SET data
  nest(data = everything(.)) %>%
  mutate(lm_mod = map(data, ~lm(Monthly_MSL_mm ~ yr, data = .x)),
         tidied = map(lm_mod, broom::tidy),
         glanced = map(lm_mod, broom::glance)) %>%
  unnest(tidied, glanced) 
  
woods_hole_slr_recent
```

## 3. Get future SLR data from the Sweet et al. 2022 report and calculate future SLR for 2090-2100

```{r}
#| message: false
#| warning: false  

woods_hole_slr_future <- read_csv(
  here::here(
    "data-raw",
    "Sea_Level_Rise_Datasets_2022",
    "SLR_TF U.S. Sea Level Projections.csv"
  ),
  skip = 17,
  col_select = c("PSMSL Site", "Scenario", "RSL2005 (cm)":"RSL2100 (cm)")
) %>%
  filter(`PSMSL Site` == "WOODS_HOLE" & str_detect(Scenario, "MED")) %>%
  mutate(scenario_name = c("low", "int_low", "int", "int_high", "high")) %>%
  mutate(rsl_2090_mm = `RSL2090 (cm)` * 10, 
         rsl_2100_mm = `RSL2100 (cm)` * 10,
         rsl_rate_mm_yr = (rsl_2100_mm - rsl_2090_mm)/10)

woods_hole_slr_future %>%
  select(`PSMSL Site`, Scenario, scenario_name, rsl_rate_mm_yr)
```

Source: 2022 Technical Report \| Resources – U.S. Sea Level Change <https://earth.gov/sealevel/us/resources/2022-sea-level-rise-technical-report/>

## 4. Save SLR data and rates to file

```{r}
#| message: false
#| warning: false

saveRDS(
  list(
    "woods_hole_slr_data" = woods_hole_slr_data,
    "woods_hole_slr_long" = woods_hole_slr_long,
    "woods_hole_slr_recent" = woods_hole_slr_recent,
    "woods_hole_slr_future" = woods_hole_slr_future
  ),
  here::here("data", "woods_hole_slr.rds")
)
```
